### ISSUE TITLE
Not able to setup dev env

### ISSUE THREAD

**Issue by aeroaks** [climatefarmers/farmdb#13]
I have forked `farmdb` and was trying to setup local dev env. But while doing `docker-compose up`, I get the following error:
```
Pulling monitoring (climatefarmers/soil-monitoring:latest)...
ERROR: manifest for climatefarmers/soil-monitoring:latest not found: manifest unknown: manifest unknown
```

**Comment by bimtauer** [comment]
Hi aeroaks, I noticed the same now as well. The reason is that our images in docker hub are not being tagged with the "latest" tag automatically. I'm introducing that fix now for all the build pipelines. In the meantime you could have a look at dockerhub climatefarmers and pick the respective sha tag that was commited last and enter it into the compose file

**Comment by bimtauer** [comment]
Latest tag should now be added to all relevant builds. I'm closing this. Thanks for raising this issue, please let me know if you encounter others :)
